### PR TITLE
engine: allow text feedback for every option + fix first selection bug

### LINKED ISSUE #1247: Feedback mechanism: Open dialog box to all radio options
### Describe the Issue

Currently we open the text box only when the user select the option 'Other'. 

We want to open text boxes to all radio options.

### PR DESCRIPTION
**Pull request by Deflaimun**
Resolves #1247

### CODE REVIEW

File: src/theme/DocItem/Layout/index.js [hunk 1]
```diff
@@ -54,9 +50,10 @@ const FeedbackForm = (props) => {
 
   const handleSubmit = (e) => {
     e.preventDefault();
-    const defaultRadio = {feedback:solvedRadio};
-    if(Object.keys(formData).length==0){
-      formData=defaultRadio;
+    const defaultRadio = solvedRadio;
+    if(!formData.feedback){
+      formData.feedback=defaultRadio;
+      console.log(formData);
```
Comment (JakeSCahill) [inline src/theme/DocItem/Layout/index.js:56]:
```suggestion
```

**Review by JakeSCahill — APPROVED** [review]
LGTM. Just remove the console log 😄
